[linux]
lab-linux-01 ansible_host=10.10.10.20

[windows]
win11-client ansible_host=10.10.10.50

[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
